# Generated by Django 5.2.7 on 2025-10-31 19:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('FARMER', 'Farmer Cooperative'), ('VENDOR', 'Vendor Cooperative'), ('DRIVER', 'Truck Driver'), ('STAFF', 'System Staff'), ('ADMIN', 'Administrator')], max_length=10, verbose_name='User Type')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('om', 'Afaan Oromo'), ('so', 'Somali')], default='am', max_length=5, verbose_name='Language Preference')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('FINANCE_MANAGER', 'Finance Manager'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('SUPPORT_STAFF', 'Support Staff')], max_length=20, verbose_name='Admin Role')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Can Manage Users')),
                ('can_manage_finances', models.BooleanField(default=False, verbose_name='Can Manage Finances')),
                ('can_manage_operations', models.BooleanField(default=False, verbose_name='Can Manage Operations')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Can View Reports')),
                ('can_configure_system', models.BooleanField(default=False, verbose_name='Can Configure System')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Login Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminprofile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True, verbose_name='Driver ID')),
                ('vehicle_type', models.CharField(choices=[('PICKUP', 'Pickup Truck'), ('MINI_TRUCK', 'Mini Truck'), ('TRUCK_3T', '3 Ton Truck'), ('TRUCK_5T', '5 Ton Truck'), ('TRUCK_10T', '10 Ton Truck'), ('OTHER', 'Other')], max_length=15, verbose_name='Vehicle Type')),
                ('vehicle_plate_number', models.CharField(max_length=20, unique=True, verbose_name='Vehicle Plate Number')),
                ('vehicle_capacity_kg', models.PositiveIntegerField(verbose_name='Vehicle Capacity (kg)')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('license_type', models.CharField(choices=[('L3', 'L3 - Light Vehicle'), ('C1', 'C1 - Medium Truck'), ('C2', 'C2 - Heavy Truck'), ('C3', 'C3 - Extra Heavy')], max_length=5, verbose_name='License Type')),
                ('license_expiry_date', models.DateField(verbose_name='License Expiry Date')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('phone_number_2', models.CharField(blank=True, max_length=15, verbose_name='Secondary Phone Number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Phone')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Earnings')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverprofile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
                'db_table': 'driver_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_name', models.CharField(max_length=255, verbose_name='Cooperative Name')),
                ('cooperative_type', models.CharField(choices=[('SMALL', 'Small Cooperative (1-10 members)'), ('MEDIUM', 'Medium Cooperative (11-50 members)'), ('LARGE', 'Large Cooperative (50+ members)')], max_length=10, verbose_name='Cooperative Type')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('total_members', models.PositiveIntegerField(default=1, verbose_name='Total Members')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Zone')),
                ('woreda', models.CharField(max_length=100, verbose_name='Woreda')),
                ('kebele', models.CharField(max_length=100, verbose_name='Kebele')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Sales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmerprofile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'db_table': 'farmer_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('business_type', models.CharField(choices=[('RETAILER', 'Retail Shop'), ('WHOLESALER', 'Wholesaler'), ('SUPERMARKET', 'Supermarket'), ('RESTAURANT', 'Restaurant/Hotel'), ('OTHER', 'Other')], max_length=15, verbose_name='Business Type')),
                ('tin_number', models.CharField(max_length=50, unique=True, verbose_name='TIN Number')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('sub_city', models.CharField(max_length=100, verbose_name='Sub City')),
                ('woreda', models.CharField(max_length=100, verbose_name='Woreda')),
                ('kebele', models.CharField(max_length=100, verbose_name='Kebele')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='House Number')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('business_license_number', models.CharField(blank=True, max_length=100, verbose_name='Business License Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit Limit')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendorprofile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'db_table': 'vendor_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
