# Generated by Django 5.2.7 on 2025-10-31 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('SOLD', 'Sold'), ('RETURNED', 'Returned')], max_length=15, verbose_name='Transaction Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Previous Quantity')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='New Quantity')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason for Change')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID (e.g., Order ID)')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Inventory Record',
                'verbose_name_plural': 'Inventory Records',
                'db_table': 'inventory_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('name_am', models.CharField(blank=True, max_length=255, verbose_name='Product Name (Amharic)')),
                ('name_om', models.CharField(blank=True, max_length=255, verbose_name='Product Name (Afaan Oromo)')),
                ('name_so', models.CharField(blank=True, max_length=255, verbose_name='Product Name (Somali)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_am', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('description_om', models.TextField(blank=True, verbose_name='Description (Afaan Oromo)')),
                ('description_so', models.TextField(blank=True, verbose_name='Description (Somali)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price per Unit')),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Liter'), ('ML', 'Milliliter'), ('PIECE', 'Piece'), ('BUNCH', 'Bunch'), ('BAG', 'Bag'), ('CRATE', 'Crate')], max_length=10, verbose_name='Unit of Measurement')),
                ('quality_grade', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('ECONOMY', 'Economy')], default='STANDARD', max_length=10, verbose_name='Quality Grade')),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Order Quantity')),
                ('max_order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Order Quantity')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available Quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Additional Images')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Is Organic')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review Count')),
                ('total_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Quantity Sold')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Product Tags')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Harvest Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('storage_instructions', models.TextField(blank=True, verbose_name='Storage Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('name_am', models.CharField(blank=True, max_length=100, verbose_name='Category Name (Amharic)')),
                ('name_om', models.CharField(blank=True, max_length=100, verbose_name='Category Name (Afaan Oromo)')),
                ('name_so', models.CharField(blank=True, max_length=100, verbose_name='Category Name (Somali)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_am', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('description_om', models.TextField(blank=True, verbose_name='Description (Afaan Oromo)')),
                ('description_so', models.TextField(blank=True, verbose_name='Description (Somali)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
